name       : python-toml
version    : 0.10.2
release    : 3
source     :
    - https://github.com/uiri/toml/archive/0.10.2.tar.gz : 71d4039bbdec91e3e7591ec5d6c943c58f9a2d17e5f6783acdc378f743fcdd2a
homepage   : https://github.com/uiri/toml
license    : MIT
component  : programming.python
summary    : Python lib for TOML
description: |
    A Python library for parsing and creating TOML.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
