name       : python-toml
version    : 0.10.0
release    : 2
source     :
    - https://github.com/uiri/toml/archive/0.10.0.tar.gz : c3821b94be15da61d631bfff45b5c58074f01149792182e68f8690829cabfcf6
license    : MIT
component  : programming.python
summary    : Python lib for TOML
description: |
    A Python library for parsing and creating TOML.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
